### ISSUE TITLE
issue#1: user can see their car

### ISSUE THREAD

**Issue by amyaitran** [amyaitran/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create and link new html, css, js files
- [x] add a green background
- [x] add a car image on top of the background
