### ISSUE TITLE
issue#2: user can turn their car

### ISSUE THREAD

**Issue by amyaitran** [amyaitran/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create css classes for the car rotated in different directions
- [x] query select for the car
- [x] add event listener when keys are pressed
- [x] change visuals for the car when keys are pressed
- [x] add css transitions for car rotations
