### ISSUE TITLE
issue#3: user can start their car

### ISSUE THREAD

**Issue by amyaitran** [amyaitran/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] create a data model
- [x] add a location to data model to hold the car's x and y coordinates on the page
- [x] add absolute positioning to the car
- [x] use the style property of element objects to change car's top and left box offset styles
- [ ] move car every 16ms
